### ISSUE TITLE
Chore: Theme Context

### ISSUE THREAD

**Issue by mr3nz1** [atlp-rwanda/matadors-rn-medica#18]
### Description
Create a custom theme context that accommodates for the different themes

### Tasks
- [x] Has a theme property
- [x] Has change theme method
- [x] Sets the favorite theme through the secure store
- [x] By default uses the device's default theme

### Dev Notes
- N/A

 ### Related Issues
- N/A

Definition of Done
- Able to use default device theme on first open
- Able to change a persistent color theme
