### ISSUE TITLE
Feature: Linking for customer service section

### ISSUE THREAD

**Issue by mr3nz1** [atlp-rwanda/matadors-rn-medica#194]
### Description
This is a linking feature for the customer service screen in the profile section

### Tasks

- [x] User can click the call listing and open the phone app where the phone number will be placed
- [x] User can open a WhatsApp chat
- [x] User is able to open medical social media via clicks
