### ISSUE TITLE
Feature: Doctor rating and review

### ISSUE THREAD

**Issue by aimeudoxie** [atlp-rwanda/matadors-rn-medica#201]
## Description
This Feature implements the functionality that will allow Users to rate  and give reviews to doctors, The user will be asked to state the number of rate stars, the review message and if they can recommend that doctor or not.

## Tasks

- [x] Adding review to a certain doctor after consultation session
- [x] Displaying reviews on Doctors' profiles
- [x] review liking
- [x] filtering reviews according to rates
