### ISSUE TITLE
Refactor: Develop structure

### ISSUE THREAD

**Issue by mr3nz1** [atlp-rwanda/matadors-rn-medica#40]
### Description
Create a custom theme context that accommodates for the different themes

### Tasks
- [x] Add files to all folder structures we had used, to avoid empty folders and allow pushing them
- [ ] Reconfigure tests
- [ ] Configure a standard expo
- [ ] Configure color schemes

### Dev Notes
- N/A

 ### Related Issues
- N/A

Definition of Done
- Able to run and navigate across already existing screens
- Well-configured color schemes
