### ISSUE TITLE
Feature: Profile & Settings Screens

### ISSUE THREAD

**Issue by mr3nz1** [atlp-rwanda/matadors-rn-medica#59]
### Description
Create mutliple screens for settings and profile section

### Tasks
- [x] Profile Screen
- [x] Edit Profile Screen                                                                   
- [x] Notifications Options Screen
- [x] Payment Screen
- [x] Security Screen
- [x] Languages Screen
- [x] Invite Friends Screen  
- [ ] Help Center

### Dev Notes
- N/A

 ### Related Issues
- N/A

Definition of Done
- Able to navigate across all those apps
